# Generated by Django 4.2.11 on 2024-04-10 14:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildMortalityRate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_year', models.IntegerField()),
                ('year', models.CharField(max_length=4, null=True)),
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('id_state', models.CharField(max_length=10, null=True)),
                ('state', models.CharField(max_length=30, null=True)),
                ('slug_state', models.CharField(max_length=30, null=True)),
                ('child_mortality', models.FloatField(null=True)),
                ('child_mortality_ci_high', models.FloatField(null=True)),
                ('child_mortality_ci_low', models.FloatField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmploymentData',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_year', models.IntegerField()),
                ('year', models.CharField(max_length=4, null=True)),
                ('geography', models.CharField(max_length=30, null=True)),
                ('id_geography', models.CharField(max_length=30, null=True)),
                ('slug_geography', models.CharField(max_length=30, null=True)),
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('id_gender', models.IntegerField(choices=[(1, 1), (2, 2)])),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True)),
                ('id_age', models.IntegerField()),
                ('age', models.CharField(max_length=3, null=True)),
                ('id_workforce_status', models.BooleanField()),
                ('workforce_status', models.CharField(max_length=5, null=True)),
                ('total_population', models.BigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EquityData',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_year', models.IntegerField()),
                ('year', models.CharField(max_length=4, null=True)),
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('id_race', models.IntegerField()),
                ('race', models.CharField(max_length=20, null=True)),
                ('id_state', models.CharField(max_length=10, null=True)),
                ('state', models.CharField(max_length=30, null=True)),
                ('slug_state', models.CharField(max_length=30, null=True)),
                ('household_income_by_race', models.FloatField(null=True)),
                ('household_income_by_race_moe', models.FloatField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HealthCareData',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_year', models.IntegerField()),
                ('year', models.CharField(max_length=4, null=True)),
                ('geography', models.CharField(max_length=30, null=True)),
                ('id_geography', models.CharField(max_length=30, null=True)),
                ('slug_geography', models.CharField(max_length=30, null=True)),
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('id_gender', models.IntegerField(choices=[(1, 1), (2, 2)])),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True)),
                ('id_health_coverage', models.IntegerField(choices=[(0, 0), (1, 1)])),
                ('health_coverage', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], max_length=7)),
                ('health_insurance_by_gender_and_age', models.BigIntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HealthProsperityIndexData',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_year', models.IntegerField()),
                ('year', models.CharField(max_length=4, null=True)),
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('employment_total_population', models.IntegerField(blank=True, null=True)),
                ('working_total_population', models.IntegerField(blank=True, null=True)),
                ('real_estate_taxes_by_mortgage', models.FloatField(blank=True, null=True)),
                ('household_income', models.FloatField(blank=True, null=True)),
                ('severe_housing_problem', models.FloatField(blank=True, null=True)),
                ('child_mortality_rate', models.FloatField(blank=True, null=True)),
                ('working_average_wage', models.FloatField(blank=True, null=True)),
                ('health_care_insurance', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HousingData',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_year', models.IntegerField()),
                ('year', models.CharField(max_length=4, null=True)),
                ('geography', models.CharField(max_length=30, null=True)),
                ('id_geography', models.CharField(max_length=30, null=True)),
                ('slug_geography', models.CharField(max_length=30, null=True)),
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('id_real_estate_taxes_paid', models.FloatField()),
                ('real_estate_taxes_paid', models.CharField(max_length=30, null=True)),
                ('real_estate_taxes_by_mortgage', models.FloatField()),
                ('real_estate_taxes_by_mortgage_moe', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PovertyData',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_year', models.IntegerField()),
                ('year', models.CharField(max_length=4, null=True)),
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('id_state', models.CharField(max_length=10, null=True)),
                ('state', models.CharField(max_length=30, null=True)),
                ('slug_state', models.CharField(max_length=30, null=True)),
                ('severe_housing_problems', models.FloatField(null=True)),
                ('severe_housing_problems_ci_high', models.FloatField(null=True)),
                ('severe_housing_problems_ci_low', models.FloatField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkingPopulationData',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_year', models.IntegerField()),
                ('year', models.CharField(max_length=4, null=True)),
                ('geography', models.CharField(max_length=30, null=True)),
                ('id_geography', models.CharField(max_length=30, null=True)),
                ('slug_geography', models.CharField(max_length=30, null=True)),
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('id_age', models.IntegerField()),
                ('age', models.CharField(max_length=3, null=True)),
                ('id_gender', models.IntegerField(choices=[(1, 1), (2, 2)])),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True)),
                ('total_population', models.BigIntegerField()),
                ('total_population_moe_appx', models.FloatField()),
                ('average_wage', models.FloatField(null=True)),
                ('average_wage_moe_appx', models.FloatField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
