# Generated by Django 4.2.11 on 2024-04-11 05:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_index_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workingpopulationdata',
            old_name='average_wage_moe_appx',
            new_name='average_wage_appx_moe',
        ),
        migrations.RemoveField(
            model_name='healthprosperityindexdata',
            name='id_year',
        ),
        migrations.AddField(
            model_name='workingpopulationdata',
            name='group',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workingpopulationdata',
            name='id_group',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='healthprosperityindexdata',
            name='year',
            field=models.CharField(default=django.utils.timezone.now, max_length=4),
            preserve_default=False,
        ),
    ]
